apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-postgres-prod
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "8e4deb8b-4156-499c-a298-546faa99f0b5"
    keyvaultName: "kv-voting-app"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""
    tenantID: "64dcbebe-0e1c-48fa-be02-d3090d747092"
  secretObjects:
  - secretName: db-secret
    type: Opaque
    data:
    - objectName: postgres-password
      key: POSTGRES_PASSWORD
